spring:
  application:
    name: demo-redis
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: gsmarin
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
